name: CI

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Run Specs with docker compose run
        run: |
          echo "***** GOING TO RUN DOCKER COMPOSE RUN. LOGS ARE EXPECTED BELOW THIS LINE *****"
          docker compose -p ci_test -f docker-compose.test.yml run --name ci_test_output ci_test sh run-tests.sh
          echo "******************* AFTER DOCKER COMPOSE *******************"
          echo "*******************"
          echo "*******************"
          echo "*******************"
          echo "*******************"
          echo "*******************"
          echo "*******************"
          echo "********* LOGS THAT SHOULD HAVE BEEN OUTPUT IN PREVIOUS STEP (reading from docker logs): *********"
          docker logs ci_test_output

      - name: Run Specs with docker run
        run: |
          echo "GOING TO DOCKER RUN"
          docker run ci_test:latest sh run-tests.sh

      - name: Run Specs with docker-compose run
        run: |
          docker compose -f docker-compose.test.yml rm -f
          echo "***** GOING TO RUN DOCKER-COMPOSE RUN. LOGS ARE EXPECTED BELOW THIS LINE *****"
          docker-compose -p ci_test -f docker-compose.test.yml run --name ci_test_output ci_test sh run-tests.sh
          echo "******************* AFTER DOCKER COMPOSE *******************"
          echo "*******************"
          echo "*******************"
          echo "*******************"
          echo "*******************"
          echo "*******************"
          echo "*******************"
          echo "********* LOGS THAT SHOULD HAVE BEEN OUTPUT IN PREVIOUS STEP (reading from docker logs): *********"
          docker logs ci_test_output
